name: go-simple-api

on:
  push:
    branches:
      - "**"

env:
  GO_VERSION: 1.22.0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      GH_API_KEY: ${{ secrets.GH_API_KEY }}
    steps:
      - name: Checkout local
        uses: actions/checkout@v3

      - name: Setup Git Config
        shell: bash
        run: |
          set -x
          git config --global user.email '${{ secrets.GH_AUTO_EMAIL }}'
          git config --global user.name '${{ secrets.GH_AUTO_USER }}'
          git config --global url.https://${GH_API_KEY}@github.com/.insteadOf https://github.com/

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.0"

      - name: Lint
        run: |
          make lint

  go-tests:
    runs-on: ubuntu-latest
    env:
      GH_API_KEY: ${{ secrets.GH_API_KEY }}
    steps:
      - name: Checkout local
        uses: actions/checkout@v3
      - name: Setup Git Config
        shell: bash
        run: |
          set -x
          git config --global user.email '${{ secrets.GH_AUTO_EMAIL }}'
          git config --global user.name '${{ secrets.GH_AUTO_USER }}'
          git config --global url.https://${GH_API_KEY}@github.com/.insteadOf https://github.com/

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.0"

      - name: go tests
        run: |
          go mod download
          go test -v ./cmd... -race
          go test -v ./internal... -race
